import type { Section, Station } from "./types";

// Заглушка сети, пока нет бэкенда: центральная часть сети, координаты реальные,
// показатели и сбои выдуманы под демо.
export const STATIONS: Station[] = [
  {
    id: "moskva-sort",
    name: "Москва-Сортировочная",
    code: "195506",
    kind: "sorting",
    lat: 55.764,
    lon: 37.708,
    efficiencyIndex: 84,
    trainCount: 46,
    trackLoad: 78,
    avgDelayMinutes: 3,
    conflictCount: 1,
    incidents: [],
  },
  {
    id: "bekasovo",
    name: "Бекасово-Сортировочное",
    code: "181405",
    kind: "sorting",
    lat: 55.396,
    lon: 36.828,
    efficiencyIndex: 48,
    trainCount: 38,
    trackLoad: 96,
    avgDelayMinutes: 41,
    conflictCount: 6,
    incidents: [
      {
        id: "bek-1",
        kind: "track-closure",
        title: "Закрыт путь 14 парка «Б» — отказ рельсовой цепи",
        startedAt: "08:42",
      },
      {
        id: "bek-2",
        kind: "route-conflict",
        title: "Пересечение маршрутов на горловине чётного парка",
        startedAt: "09:05",
      },
      {
        id: "bek-3",
        kind: "resource-shortage",
        title: "Не хватает маневровых локомотивов: 2 из 4",
        startedAt: "09:11",
      },
    ],
  },
  {
    id: "orekhovo",
    name: "Орехово-Зуево",
    code: "232003",
    kind: "freight",
    lat: 55.812,
    lon: 38.976,
    efficiencyIndex: 88,
    trainCount: 14,
    trackLoad: 52,
    avgDelayMinutes: 2,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "vladimir",
    name: "Владимир",
    code: "240002",
    kind: "passenger",
    lat: 56.129,
    lon: 40.409,
    efficiencyIndex: 81,
    trainCount: 18,
    trackLoad: 64,
    avgDelayMinutes: 5,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "nizhny-sort",
    name: "Нижний Новгород-Сорт.",
    code: "247601",
    kind: "sorting",
    lat: 56.302,
    lon: 43.883,
    efficiencyIndex: 69,
    trainCount: 31,
    trackLoad: 87,
    avgDelayMinutes: 17,
    conflictCount: 3,
    incidents: [
      {
        id: "nnov-1",
        kind: "delay",
        title: "Опоздание грузового №2614 на 47 мин",
        startedAt: "08:58",
      },
    ],
  },
  {
    id: "murom",
    name: "Муром I",
    code: "244001",
    kind: "junction",
    lat: 55.566,
    lon: 42.052,
    efficiencyIndex: 86,
    trainCount: 9,
    trackLoad: 41,
    avgDelayMinutes: 2,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "aleksandrov",
    name: "Александров I",
    code: "300007",
    kind: "junction",
    lat: 56.395,
    lon: 38.716,
    efficiencyIndex: 83,
    trainCount: 16,
    trackLoad: 58,
    avgDelayMinutes: 4,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "yaroslavl",
    name: "Ярославль-Главный",
    code: "310007",
    kind: "passenger",
    lat: 57.627,
    lon: 39.846,
    efficiencyIndex: 72,
    trainCount: 22,
    trackLoad: 81,
    avgDelayMinutes: 12,
    conflictCount: 2,
    incidents: [
      {
        id: "yar-1",
        kind: "breakdown",
        title: "Отказ стрелочного перевода №17",
        startedAt: "09:20",
      },
    ],
  },
  {
    id: "kostroma",
    name: "Кострома",
    code: "311003",
    kind: "passenger",
    lat: 57.763,
    lon: 40.935,
    efficiencyIndex: 90,
    trainCount: 7,
    trackLoad: 36,
    avgDelayMinutes: 1,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "ivanovo",
    name: "Иваново",
    code: "301005",
    kind: "passenger",
    lat: 56.998,
    lon: 40.972,
    efficiencyIndex: 87,
    trainCount: 8,
    trackLoad: 44,
    avgDelayMinutes: 3,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "tver",
    name: "Тверь",
    code: "061502",
    kind: "passenger",
    lat: 56.835,
    lon: 35.894,
    efficiencyIndex: 85,
    trainCount: 21,
    trackLoad: 61,
    avgDelayMinutes: 3,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "rzhev",
    name: "Ржев-Балтийский",
    code: "063004",
    kind: "junction",
    lat: 56.255,
    lon: 34.323,
    efficiencyIndex: 79,
    trainCount: 6,
    trackLoad: 48,
    avgDelayMinutes: 6,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "vyazma",
    name: "Вязьма",
    code: "174001",
    kind: "junction",
    lat: 55.21,
    lon: 34.288,
    efficiencyIndex: 74,
    trainCount: 15,
    trackLoad: 76,
    avgDelayMinutes: 9,
    conflictCount: 1,
    incidents: [
      {
        id: "vya-1",
        kind: "resource-shortage",
        title: "Нет свободной локомотивной бригады под поезд №1408",
        startedAt: "09:02",
      },
    ],
  },
  {
    id: "smolensk-sort",
    name: "Смоленск-Сорт.",
    code: "170201",
    kind: "sorting",
    lat: 54.786,
    lon: 32.058,
    efficiencyIndex: 82,
    trainCount: 19,
    trackLoad: 66,
    avgDelayMinutes: 4,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "kaluga",
    name: "Калуга I",
    code: "180003",
    kind: "passenger",
    lat: 54.512,
    lon: 36.251,
    efficiencyIndex: 86,
    trainCount: 11,
    trackLoad: 47,
    avgDelayMinutes: 2,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "bryansk",
    name: "Брянск-Льговский",
    code: "192007",
    kind: "junction",
    lat: 53.212,
    lon: 34.369,
    efficiencyIndex: 80,
    trainCount: 13,
    trackLoad: 59,
    avgDelayMinutes: 5,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "tula",
    name: "Тула I-Курская",
    code: "210001",
    kind: "passenger",
    lat: 54.177,
    lon: 37.619,
    efficiencyIndex: 77,
    trainCount: 17,
    trackLoad: 70,
    avgDelayMinutes: 7,
    conflictCount: 1,
    incidents: [],
  },
  {
    id: "orel",
    name: "Орёл",
    code: "208001",
    kind: "junction",
    lat: 52.969,
    lon: 36.083,
    efficiencyIndex: 83,
    trainCount: 14,
    trackLoad: 55,
    avgDelayMinutes: 4,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "uzlovaya",
    name: "Узловая I",
    code: "213002",
    kind: "sorting",
    lat: 53.983,
    lon: 38.164,
    efficiencyIndex: 52,
    trainCount: 27,
    trackLoad: 93,
    avgDelayMinutes: 34,
    conflictCount: 5,
    incidents: [
      {
        id: "uzl-1",
        kind: "breakdown",
        title: "Неисправность вагона в составе №3312 — отцепка",
        startedAt: "08:36",
      },
      {
        id: "uzl-2",
        kind: "delay",
        title: "Задержка расформирования: 4 состава в ожидании",
        startedAt: "08:50",
      },
    ],
  },
  {
    id: "elets",
    name: "Елец",
    code: "590004",
    kind: "junction",
    lat: 52.616,
    lon: 38.497,
    efficiencyIndex: 81,
    trainCount: 12,
    trackLoad: 57,
    avgDelayMinutes: 5,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "rybnoe",
    name: "Рыбное",
    code: "221003",
    kind: "sorting",
    lat: 54.731,
    lon: 39.511,
    efficiencyIndex: 78,
    trainCount: 24,
    trackLoad: 72,
    avgDelayMinutes: 6,
    conflictCount: 1,
    incidents: [],
  },
  {
    id: "ryazhsk",
    name: "Ряжск I",
    code: "602002",
    kind: "junction",
    lat: 53.708,
    lon: 40.063,
    efficiencyIndex: 85,
    trainCount: 10,
    trackLoad: 49,
    avgDelayMinutes: 3,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "kochetovka",
    name: "Кочетовка I",
    code: "605005",
    kind: "sorting",
    lat: 52.955,
    lon: 40.523,
    efficiencyIndex: 76,
    trainCount: 20,
    trackLoad: 74,
    avgDelayMinutes: 8,
    conflictCount: 1,
    incidents: [],
  },
];

export const SECTIONS: Section[] = [
  section("moskva-sort", "orekhovo"),
  section("orekhovo", "vladimir"),
  section("vladimir", "nizhny-sort", "warning", "Ограничение скорости 60 км/ч"),
  section("vladimir", "murom"),
  section("moskva-sort", "aleksandrov"),
  section("aleksandrov", "yaroslavl"),
  section("yaroslavl", "kostroma"),
  section("yaroslavl", "ivanovo"),
  section("moskva-sort", "tver"),
  section("tver", "rzhev"),
  section("rzhev", "vyazma"),
  section(
    "moskva-sort",
    "bekasovo",
    "critical",
    "Очередь из 5 поездов на подходе",
  ),
  section("bekasovo", "vyazma", "warning", "Окно ТО 10:00–12:00"),
  section("vyazma", "smolensk-sort"),
  section("bekasovo", "kaluga"),
  section("kaluga", "bryansk"),
  section("bryansk", "orel"),
  section("moskva-sort", "tula"),
  section("tula", "orel"),
  section("tula", "uzlovaya", "critical", "Ожидание приёма на станцию"),
  section("uzlovaya", "elets"),
  section("orel", "elets"),
  section("moskva-sort", "rybnoe"),
  section("rybnoe", "ryazhsk"),
  section("uzlovaya", "ryazhsk"),
  section("ryazhsk", "kochetovka"),
];

function section(
  fromId: string,
  toId: string,
  status: Section["status"] = "normal",
  note?: string,
): Section {
  return { id: `${fromId}--${toId}`, fromId, toId, status, note };
}
