import type { Section, Station } from "./types";

// Заглушка сети, пока нет бэкенда: магистрали Казахстана, станции и координаты
// реальные, коды ЕСР, показатели и сбои выдуманы под демо.
export const STATIONS: Station[] = [
  {
    id: "almaty-1",
    name: "Алматы-1",
    code: "700009",
    kind: "sorting",
    lat: 43.341,
    lon: 76.948,
    efficiencyIndex: 53,
    trainCount: 34,
    trackLoad: 94,
    avgDelayMinutes: 36,
    conflictCount: 5,
    incidents: [
      {
        id: "almaty-1-1",
        kind: "delay",
        title: "Задержка расформирования: 5 составов в ожидании",
        startedAt: "08:34",
      },
      {
        id: "almaty-1-2",
        kind: "track-closure",
        title: "Закрыт путь 7 сортировочного парка — отказ рельсовой цепи",
        startedAt: "08:51",
      },
    ],
  },
  {
    id: "altynkol",
    name: "Алтынколь",
    code: "702200",
    kind: "freight",
    lat: 44.171,
    lon: 80.395,
    efficiencyIndex: 77,
    trainCount: 9,
    trackLoad: 68,
    avgDelayMinutes: 8,
    conflictCount: 1,
    incidents: [],
  },
  {
    id: "sary-ozek",
    name: "Сары-Озек",
    code: "701802",
    kind: "junction",
    lat: 44.36,
    lon: 77.97,
    efficiencyIndex: 84,
    trainCount: 7,
    trackLoad: 42,
    avgDelayMinutes: 3,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "ushtobe",
    name: "Уштобе",
    code: "701600",
    kind: "junction",
    lat: 45.25,
    lon: 77.985,
    efficiencyIndex: 86,
    trainCount: 8,
    trackLoad: 39,
    avgDelayMinutes: 2,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "aktogay",
    name: "Актогай",
    code: "704009",
    kind: "sorting",
    lat: 46.948,
    lon: 79.664,
    efficiencyIndex: 72,
    trainCount: 26,
    trackLoad: 83,
    avgDelayMinutes: 14,
    conflictCount: 2,
    incidents: [
      {
        id: "aktogay-1",
        kind: "route-conflict",
        title: "Пересечение маршрутов приёма с направлений Достык и Мойынты",
        startedAt: "09:07",
      },
    ],
  },
  {
    id: "dostyk",
    name: "Достык",
    code: "705304",
    kind: "freight",
    lat: 45.252,
    lon: 82.48,
    efficiencyIndex: 47,
    trainCount: 19,
    trackLoad: 97,
    avgDelayMinutes: 52,
    conflictCount: 4,
    incidents: [
      {
        id: "dostyk-1",
        kind: "resource-shortage",
        title: "Перегрузочный терминал работает на 100%: 9 поездов в очереди",
        startedAt: "07:58",
      },
      {
        id: "dostyk-2",
        kind: "breakdown",
        title: "Отказ козлового крана на перестановке колёсных пар",
        startedAt: "08:40",
      },
      {
        id: "dostyk-3",
        kind: "delay",
        title: "Опоздание контейнерного №8102 на 2 ч 15 мин",
        startedAt: "09:12",
      },
    ],
  },
  {
    id: "ayagoz",
    name: "Аягоз",
    code: "706006",
    kind: "junction",
    lat: 47.965,
    lon: 80.437,
    efficiencyIndex: 85,
    trainCount: 9,
    trackLoad: 45,
    avgDelayMinutes: 3,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "zhangiz-tobe",
    name: "Жангизтобе",
    code: "707505",
    kind: "junction",
    lat: 49.215,
    lon: 81.215,
    efficiencyIndex: 83,
    trainCount: 10,
    trackLoad: 51,
    avgDelayMinutes: 4,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "semey",
    name: "Семей",
    code: "707006",
    kind: "passenger",
    lat: 50.405,
    lon: 80.247,
    efficiencyIndex: 73,
    trainCount: 14,
    trackLoad: 77,
    avgDelayMinutes: 11,
    conflictCount: 1,
    incidents: [
      {
        id: "semey-1",
        kind: "delay",
        title: "Опоздание пассажирского №354 на 38 мин",
        startedAt: "09:15",
      },
    ],
  },
  {
    id: "shu",
    name: "Шу",
    code: "690005",
    kind: "sorting",
    lat: 43.598,
    lon: 73.762,
    efficiencyIndex: 79,
    trainCount: 21,
    trackLoad: 71,
    avgDelayMinutes: 6,
    conflictCount: 1,
    incidents: [],
  },
  {
    id: "taraz",
    name: "Тараз",
    code: "694003",
    kind: "passenger",
    lat: 42.885,
    lon: 71.385,
    efficiencyIndex: 87,
    trainCount: 12,
    trackLoad: 47,
    avgDelayMinutes: 2,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "shymkent",
    name: "Шымкент",
    code: "698002",
    kind: "passenger",
    lat: 42.317,
    lon: 69.596,
    efficiencyIndex: 81,
    trainCount: 16,
    trackLoad: 62,
    avgDelayMinutes: 5,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "arys",
    name: "Арысь-1",
    code: "698303",
    kind: "sorting",
    lat: 42.43,
    lon: 68.807,
    efficiencyIndex: 76,
    trainCount: 23,
    trackLoad: 74,
    avgDelayMinutes: 7,
    conflictCount: 1,
    incidents: [],
  },
  {
    id: "saryagash",
    name: "Сарыагаш",
    code: "698608",
    kind: "freight",
    lat: 41.46,
    lon: 69.17,
    efficiencyIndex: 74,
    trainCount: 13,
    trackLoad: 79,
    avgDelayMinutes: 13,
    conflictCount: 1,
    incidents: [
      {
        id: "saryagash-1",
        kind: "resource-shortage",
        title: "Нет свободной локомотивной бригады под поезд №2731",
        startedAt: "09:03",
      },
    ],
  },
  {
    id: "turkestan",
    name: "Туркестан",
    code: "674001",
    kind: "passenger",
    lat: 43.297,
    lon: 68.252,
    efficiencyIndex: 89,
    trainCount: 8,
    trackLoad: 38,
    avgDelayMinutes: 2,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "kyzylorda",
    name: "Кызылорда",
    code: "672004",
    kind: "passenger",
    lat: 44.845,
    lon: 65.505,
    efficiencyIndex: 84,
    trainCount: 10,
    trackLoad: 46,
    avgDelayMinutes: 3,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "kazaly",
    name: "Казалы",
    code: "670209",
    kind: "junction",
    lat: 45.763,
    lon: 62.107,
    efficiencyIndex: 88,
    trainCount: 6,
    trackLoad: 35,
    avgDelayMinutes: 2,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "saksaulskaya",
    name: "Саксаульская",
    code: "668301",
    kind: "junction",
    lat: 47.083,
    lon: 61.163,
    efficiencyIndex: 82,
    trainCount: 7,
    trackLoad: 44,
    avgDelayMinutes: 4,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "shalkar",
    name: "Шалкар",
    code: "667201",
    kind: "junction",
    lat: 47.833,
    lon: 59.62,
    efficiencyIndex: 80,
    trainCount: 9,
    trackLoad: 49,
    avgDelayMinutes: 5,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "kandyagash",
    name: "Кандыагаш",
    code: "664208",
    kind: "sorting",
    lat: 49.47,
    lon: 57.42,
    efficiencyIndex: 78,
    trainCount: 20,
    trackLoad: 70,
    avgDelayMinutes: 6,
    conflictCount: 1,
    incidents: [],
  },
  {
    id: "aktobe",
    name: "Актобе-1",
    code: "663009",
    kind: "passenger",
    lat: 50.283,
    lon: 57.168,
    efficiencyIndex: 85,
    trainCount: 15,
    trackLoad: 55,
    avgDelayMinutes: 3,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "makat",
    name: "Макат",
    code: "662103",
    kind: "junction",
    lat: 47.65,
    lon: 53.32,
    efficiencyIndex: 83,
    trainCount: 7,
    trackLoad: 41,
    avgDelayMinutes: 3,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "atyrau",
    name: "Атырау",
    code: "661800",
    kind: "passenger",
    lat: 47.1,
    lon: 51.92,
    efficiencyIndex: 86,
    trainCount: 9,
    trackLoad: 48,
    avgDelayMinutes: 2,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "beyneu",
    name: "Бейнеу",
    code: "662600",
    kind: "junction",
    lat: 45.32,
    lon: 55.195,
    efficiencyIndex: 77,
    trainCount: 12,
    trackLoad: 67,
    avgDelayMinutes: 7,
    conflictCount: 1,
    incidents: [],
  },
  {
    id: "mangyshlak",
    name: "Мангышлак",
    code: "663200",
    kind: "freight",
    lat: 43.68,
    lon: 51.7,
    efficiencyIndex: 70,
    trainCount: 13,
    trackLoad: 82,
    avgDelayMinutes: 16,
    conflictCount: 2,
    incidents: [
      {
        id: "mangyshlak-1",
        kind: "breakdown",
        title: "Отказ стрелочного перевода №12 на подходе к порту",
        startedAt: "08:47",
      },
    ],
  },
  {
    id: "zhezkazgan",
    name: "Жезказган",
    code: "676502",
    kind: "freight",
    lat: 47.795,
    lon: 67.705,
    efficiencyIndex: 85,
    trainCount: 8,
    trackLoad: 43,
    avgDelayMinutes: 3,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "zharyk",
    name: "Жарык",
    code: "678703",
    kind: "junction",
    lat: 48.85,
    lon: 72.865,
    efficiencyIndex: 87,
    trainCount: 6,
    trackLoad: 37,
    avgDelayMinutes: 2,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "karaganda",
    name: "Караганды-Сорт.",
    code: "680006",
    kind: "sorting",
    lat: 49.805,
    lon: 73.095,
    efficiencyIndex: 81,
    trainCount: 29,
    trackLoad: 69,
    avgDelayMinutes: 5,
    conflictCount: 1,
    incidents: [],
  },
  {
    id: "moyynty",
    name: "Мойынты",
    code: "679103",
    kind: "junction",
    lat: 47.218,
    lon: 73.358,
    efficiencyIndex: 82,
    trainCount: 9,
    trackLoad: 46,
    avgDelayMinutes: 4,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "balkhash",
    name: "Балхаш",
    code: "679301",
    kind: "freight",
    lat: 46.85,
    lon: 74.98,
    efficiencyIndex: 88,
    trainCount: 5,
    trackLoad: 33,
    avgDelayMinutes: 1,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "astana",
    name: "Астана-1",
    code: "684001",
    kind: "sorting",
    lat: 51.193,
    lon: 71.41,
    efficiencyIndex: 71,
    trainCount: 31,
    trackLoad: 85,
    avgDelayMinutes: 13,
    conflictCount: 3,
    incidents: [
      {
        id: "astana-1",
        kind: "route-conflict",
        title: "Пересечение маршрутов в горловине чётного парка",
        startedAt: "08:55",
      },
      {
        id: "astana-2",
        kind: "delay",
        title: "Опоздание грузового №3118 на 52 мин",
        startedAt: "09:09",
      },
    ],
  },
  {
    id: "ekibastuz",
    name: "Экибастуз-1",
    code: "685303",
    kind: "freight",
    lat: 51.725,
    lon: 75.325,
    efficiencyIndex: 79,
    trainCount: 22,
    trackLoad: 73,
    avgDelayMinutes: 6,
    conflictCount: 1,
    incidents: [],
  },
  {
    id: "pavlodar",
    name: "Павлодар",
    code: "686001",
    kind: "passenger",
    lat: 52.285,
    lon: 76.95,
    efficiencyIndex: 84,
    trainCount: 12,
    trackLoad: 52,
    avgDelayMinutes: 3,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "kokshetau",
    name: "Кокшетау-1",
    code: "683006",
    kind: "passenger",
    lat: 53.285,
    lon: 69.395,
    efficiencyIndex: 87,
    trainCount: 11,
    trackLoad: 45,
    avgDelayMinutes: 2,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "petropavl",
    name: "Петропавловск",
    code: "682302",
    kind: "junction",
    lat: 54.87,
    lon: 69.13,
    efficiencyIndex: 83,
    trainCount: 17,
    trackLoad: 60,
    avgDelayMinutes: 4,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "esil",
    name: "Есиль",
    code: "687006",
    kind: "junction",
    lat: 51.955,
    lon: 66.405,
    efficiencyIndex: 85,
    trainCount: 6,
    trackLoad: 38,
    avgDelayMinutes: 3,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "tobol",
    name: "Тобол",
    code: "688205",
    kind: "sorting",
    lat: 52.7,
    lon: 62.58,
    efficiencyIndex: 82,
    trainCount: 14,
    trackLoad: 57,
    avgDelayMinutes: 4,
    conflictCount: 0,
    incidents: [],
  },
  {
    id: "kostanay",
    name: "Костанай",
    code: "688004",
    kind: "passenger",
    lat: 53.21,
    lon: 63.625,
    efficiencyIndex: 89,
    trainCount: 8,
    trackLoad: 41,
    avgDelayMinutes: 2,
    conflictCount: 0,
    incidents: [],
  },
];

export const SECTIONS: Section[] = [
  // Турксиб
  section("semey", "zhangiz-tobe"),
  section("zhangiz-tobe", "ayagoz"),
  section("ayagoz", "aktogay"),
  section(
    "aktogay",
    "dostyk",
    "critical",
    "Очередь из 9 контейнерных поездов на погранпереход",
  ),
  section("aktogay", "ushtobe"),
  section("ushtobe", "sary-ozek"),
  section("sary-ozek", "almaty-1", "warning", "Ожидание приёма на станцию"),
  section("almaty-1", "altynkol"),
  section("almaty-1", "shu", "warning", "Окно ТО 10:00–12:00"),
  section("shu", "taraz"),
  section("taraz", "shymkent"),
  section("shymkent", "arys"),
  section("arys", "saryagash", "warning", "Очередь на передачу в Узбекистан"),
  // Трансаральская магистраль
  section("arys", "turkestan"),
  section("turkestan", "kyzylorda"),
  section("kyzylorda", "kazaly"),
  section("kazaly", "saksaulskaya"),
  section("saksaulskaya", "shalkar"),
  section("shalkar", "kandyagash"),
  section("kandyagash", "aktobe"),
  // Запад: Каспий и Мангышлак
  section("kandyagash", "makat"),
  section("makat", "atyrau"),
  section("makat", "beyneu"),
  section("shalkar", "beyneu"),
  section("beyneu", "mangyshlak", "warning", "Ограничение скорости 40 км/ч"),
  section("zhezkazgan", "saksaulskaya"),
  // Центр и север
  section("petropavl", "kokshetau"),
  section("kokshetau", "astana"),
  section("astana", "karaganda"),
  section("karaganda", "zharyk"),
  section("zharyk", "zhezkazgan"),
  section("zharyk", "moyynty"),
  section("moyynty", "shu"),
  section("moyynty", "balkhash"),
  section("moyynty", "aktogay"),
  section("astana", "ekibastuz"),
  section("ekibastuz", "pavlodar"),
  section("astana", "esil"),
  section("esil", "tobol"),
  section("tobol", "kostanay"),
];

function section(
  fromId: string,
  toId: string,
  status: Section["status"] = "normal",
  note?: string,
): Section {
  return { id: `${fromId}--${toId}`, fromId, toId, status, note };
}
